import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';

const db = new DatabaseSync(process.env.DB_PATH || './workboard.sqlite');
db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS projects (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE, title TEXT NOT NULL, completed INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
if (!db.prepare('PRAGMA table_info(projects)').all().some(c => c.name === 'archived')) db.exec('ALTER TABLE projects ADD COLUMN archived INTEGER NOT NULL DEFAULT 0');
const listProjects = db.prepare(`SELECT p.id,p.name,p.archived,COUNT(t.id) total_count,COALESCE(SUM(t.completed),0) completed_count FROM projects p LEFT JOIN tasks t ON t.project_id=p.id WHERE p.archived=? GROUP BY p.id ORDER BY p.id`);
const getProject = db.prepare('SELECT id,name,archived FROM projects WHERE id=?');
const createProject = db.prepare('INSERT INTO projects(name) VALUES(?)');
const setArchived = db.prepare('UPDATE projects SET archived=? WHERE id=?');
const listTasks = db.prepare('SELECT id,title,completed FROM tasks WHERE project_id=? ORDER BY id');
const createTask = db.prepare('INSERT INTO tasks(project_id,title) VALUES(?,?)');
const updateTask = db.prepare('UPDATE tasks SET completed=? WHERE id=? AND project_id=?');
const page = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Workboard</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f6fa;color:#202b3c;font:16px system-ui,sans-serif}main{max-width:760px;margin:64px auto;padding:0 24px}h1{font-size:32px;margin:0 0 28px}form{display:flex;gap:12px;margin:18px 0 24px}input,select{flex:1;min-width:0;padding:12px 14px;border:1px solid #bdc7d5;border-radius:6px;font:inherit}button{border:0;border-radius:6px;padding:11px 16px;background:#2659c7;color:white;font:inherit;cursor:pointer;margin-left:5px}button:disabled{opacity:.55;cursor:default}.row{display:flex;align-items:center;justify-content:space-between;gap:16px;background:white;border:1px solid #dce2eb;border-radius:7px;padding:14px 16px;margin:10px 0}.row-name{overflow-wrap:anywhere}.alert{color:#a11;font-weight:600;margin:0 0 16px}[hidden]{display:none!important}.back{margin:0 0 22px}.task-row{justify-content:flex-start}.task-row input{flex:initial}.summary{white-space:nowrap}</style></head><body><main><section id="list-view"><h1>Workboard</h1><label>Project filter <select id="project-filter"><option>Active</option><option>Archived</option></select></label><form id="create-form"><input id="project-name" aria-label="Project name" placeholder="Project name"><button>Create project</button></form><p id="error" class="alert" role="alert" hidden></p><div id="projects"></div></section><section id="project-view" hidden><button id="back" class="back" type="button">Projects</button><p id="archived-notice" hidden>Archived project</p><h1 id="project-title"></h1><form id="task-form"><input id="task-title" aria-label="Task title" placeholder="Task title"><button>Create task</button></form><p id="task-error" class="alert" role="alert" hidden></p><label>Task filter <select id="task-filter"><option>All</option><option>Open</option><option>Completed</option></select></label><div id="tasks"></div></section></main><script>
const listView=document.querySelector('#list-view'),projectView=document.querySelector('#project-view'),projects=document.querySelector('#projects'),error=document.querySelector('#error'),tasks=document.querySelector('#tasks');let activeProject=null,allTasks=[],currentProject=null;
async function request(url,options){const r=await fetch(url,options);if(!r.ok)throw Error('Request failed');return r.json()}function action(method,data){return{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}}
async function renderRows(){const archived=document.querySelector('#project-filter').value==='Archived';const rows=await request('/api/projects?archived='+archived);projects.replaceChildren(...rows.map(p=>{const row=document.createElement('div');row.className='row';row.dataset.testid='project-row';const name=document.createElement('span');name.className='row-name';name.textContent=p.name;const summary=document.createElement('span');summary.dataset.testid='project-summary';summary.className='summary';summary.textContent=p.completed_count+'/'+p.total_count+' completed';const open=document.createElement('button');open.textContent='Open project';open.onclick=()=>{history.pushState({},'','/projects/'+p.id);showRoute()};const toggle=document.createElement('button');toggle.textContent=archived?'Restore project':'Archive project';toggle.onclick=async()=>{await request('/api/projects/'+p.id,action('PATCH',{archived:!archived}));renderRows()};row.append(name,summary,open,toggle);return row}))}
function renderTasks(){const f=document.querySelector('#task-filter').value,shown=allTasks.filter(t=>f==='All'||(f==='Open'?!t.completed:!!t.completed));tasks.replaceChildren(...shown.map(t=>{const row=document.createElement('div');row.className='row task-row';row.dataset.testid='task-row';const title=document.createElement('span');title.className='row-name';title.textContent=t.title;const check=document.createElement('input');check.type='checkbox';check.checked=!!t.completed;check.disabled=!!currentProject.archived;check.setAttribute('aria-label','Complete '+t.title);check.onchange=async()=>{await request('/api/projects/'+activeProject+'/tasks/'+t.id,action('PATCH',{completed:check.checked}));t.completed=check.checked;renderTasks()};row.append(title,check);return row}))}
async function showRoute(){const m=location.pathname.match(/^\\/projects\\/(\\d+)\\/?$/);if(m){try{activeProject=m[1];currentProject=await request('/api/projects/'+activeProject);listView.hidden=true;projectView.hidden=false;document.querySelector('#project-title').textContent=currentProject.name;document.querySelector('#archived-notice').hidden=!currentProject.archived;document.querySelector('#task-form button').disabled=!!currentProject.archived;allTasks=await request('/api/projects/'+activeProject+'/tasks');renderTasks()}catch{history.replaceState({},'','/');showRoute()}return}activeProject=null;currentProject=null;projectView.hidden=true;listView.hidden=false;await renderRows()}
document.querySelector('#create-form').onsubmit=async e=>{e.preventDefault();const input=document.querySelector('#project-name'),name=input.value.trim();if(!name){error.textContent='Project name is required';error.hidden=false;return}error.hidden=true;await request('/api/projects',action('POST',{name}));input.value='';await renderRows()};document.querySelector('#task-form').onsubmit=async e=>{e.preventDefault();const input=document.querySelector('#task-title'),title=input.value.trim(),msg=document.querySelector('#task-error');if(!title){msg.textContent='Task title is required';msg.hidden=false;return}msg.hidden=true;await request('/api/projects/'+activeProject+'/tasks',action('POST',{title}));input.value='';allTasks=await request('/api/projects/'+activeProject+'/tasks');renderTasks()};document.querySelector('#task-filter').onchange=renderTasks;document.querySelector('#project-filter').onchange=renderRows;document.querySelector('#back').onclick=()=>{history.pushState({},'','/');showRoute()};addEventListener('popstate',showRoute);showRoute();
</script></body></html>`;
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'X-Content-Type-Options':'nosniff'});res.end(typeof body==='string'?body:JSON.stringify(body))}
async function readBody(req){let s='';for await(const c of req){s+=c;if(s.length>10000)throw Error('Too large')}return JSON.parse(s)}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost'),path=url.pathname;if(req.method==='GET'&&path==='/health')return send(res,200,{status:'ok'});if(req.method==='GET'&&path==='/api/projects')return send(res,200,listProjects.all(url.searchParams.get('archived')==='true'?1:0));if(req.method==='GET'&&/^\/api\/projects\/\d+$/.test(path)){const p=getProject.get(Number(path.split('/').pop()));return p?send(res,200,p):send(res,404,{error:'Not found'})}const tm=path.match(/^\/api\/projects\/(\d+)\/tasks(?:\/(\d+))?$/);if(tm){const pid=Number(tm[1]),p=getProject.get(pid);if(!p)return send(res,404,{error:'Not found'});if(req.method==='GET'&&!tm[2])return send(res,200,listTasks.all(pid));try{const d=await readBody(req);if(req.method==='POST'&&!tm[2]){if(p.archived)return send(res,403,{error:'Archived project'});const title=String(d.title??'').trim();if(!title)return send(res,400,{error:'Task title is required'});const r=createTask.run(pid,title);return send(res,201,{id:Number(r.lastInsertRowid),title,completed:0})}if(req.method==='PATCH'&&tm[2]){if(p.archived)return send(res,403,{error:'Archived project'});const r=updateTask.run(d.completed?1:0,Number(tm[2]),pid);return r.changes?send(res,200,{ok:true}):send(res,404,{error:'Not found'})}}catch{return send(res,400,{error:'Invalid request'})}}if(req.method==='PATCH'&&/^\/api\/projects\/\d+$/.test(path)){try{const d=await readBody(req),id=Number(path.split('/').pop());if(!getProject.get(id))return send(res,404,{error:'Not found'});setArchived.run(d.archived?1:0,id);return send(res,200,{ok:true})}catch{return send(res,400,{error:'Invalid request'})}}if(req.method==='POST'&&path==='/api/projects'){try{const d=await readBody(req),name=String(d.name??'').trim();if(!name)return send(res,400,{error:'Project name is required'});const r=createProject.run(name);return send(res,201,{id:Number(r.lastInsertRowid),name})}catch{return send(res,400,{error:'Invalid request'})}}if(req.method==='GET'&&(path==='/'||/^\/projects\/\d+\/?$/.test(path)))return send(res,200,page,'text/html; charset=utf-8');send(res,404,{error:'Not found'})});
server.listen(Number(process.env.PORT)||8080,'0.0.0.0');
